### ISSUE TITLE
关于“阅读全文”的 html 标签的小问题

### ISSUE THREAD

**Issue by KagamiChan** [overtrue/wp-cn-excerpt#1]
试用了一下插件，个人觉得很不错，但是有一些小问题想请教一下
1. HTML Class Name 的命名风格，一般来说都是用`-`而不是`_`（例如http://google-styleguide.googlecode.com/svn/trunk/htmlcssguide.xml?showone=ID_and_class_name_delimiters#ID_and_class_name_delimiters）， 不知道插件使用`read_more`是不是有避免重名的考虑？
2. 是否可以考虑在`<a>`外部增加一个`<span>`以增强可能的样式定制性？

**Comment by overtrue** [comment]
OK，近期较为繁忙，已经整理相关需求，多谢反馈，我会抽时间更新！

**Comment by overtrue** [comment]
@KagamiChan 已经支持自定义模板功能 :smiley:
