### ISSUE TITLE
这个插件和rtmedia插件冲突

### ISSUE THREAD

**Issue by tangmeng09** [overtrue/wp-cn-excerpt#2]
新版本才有的问题。4.2.8版是好的。
这个插件一启用，rtmedia就不工作了。群组的多媒体页面就没了。
还好只是个人电脑里升级试了一下，真正网站没升级。

**Comment by overtrue** [comment]
1. 这个与主题输出函数the_content,the_excerpt等函数相关，不同的主题或者插件可能都在这两函数上有钩子（有相关的处理逻辑），没法兼容所有的主题与插件。
