### ISSUE TITLE
文章长度小于摘要

### ISSUE THREAD

**Issue by kurtwong** [overtrue/wp-cn-excerpt#6]
插件不错，不过我发现一个问题。
比如，文章只有一段，而摘要也是一段。 此时，就不要在尾部添加“阅读全文”。
还有长度也是如此。

**Comment by overtrue** [comment]
如果不加该链接，别人会认为是 Bug, 而且，就算文章只有一段，也需要 “进入文章详情页” 这样的需求啊

**Comment by kurtwong** [comment]
可以点标题进入 "文章详情页"。
不过，我自己在电脑上改了，只针对长度摘要时处理了一下。
我引用了你仓库的副本，增加了一个全局变量识别。
