### ISSUE TITLE
在设置“全文链接”的时候有乱码

### ISSUE THREAD

**Issue by muguiping** [overtrue/wp-cn-excerpt#7]
刚刚才发现，原来我有两款正在使用的插件都是你的作品，真厉害。
在设置“全文链接”的位置会有乱码，文字填写进去之后，一点“保存设置”就会变成乱码，但是在摘要的位置显示的是正常文字。
`<a href=":url" class="read-more">é��è¯»æ�´å¤�</a>`

**Comment by overtrue** [comment]
@muguiping 哈哈，这都是大学时期的作品了，应该有7年多历史了，我抽空更新一下

**Comment by muguiping** [comment]
回复的好快，谢谢谢谢！
在wp-auto-top也有个问题，麻烦你看看

**Comment by overtrue** [comment]
@muguiping 你的版本是什么字符集，我刚才安装了一个 wordpress 没有发现保存后有乱码现象。如果你使用 GBK 版本的话，可能需要改一下字符集了，另外就是确认一下你的数据库字符集为 UTF-8

**Comment by muguiping** [comment]
wp-config.php中是这样的：
‘/** 创建数据表时默认的文字编码 */
define('DB_CHARSET', 'utf8mb4');’
phpmyadmin里面是这样的：
`服务器: 服务器1 (Localhost via UNIX socket)
服务器类型: MySQL
服务器版本: 5.5.50-log - MySQL Community Server (GPL)
协议版本: 10
用户: root@localhost
服务器字符集: UTF-8 Unicode (utf8)`

上面那个有mb4，下面没有，果然不一样。
